//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Surename { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SeriaPassport { get; set; }
        public string NumberPassport { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> CorparationId { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
